version: '3.1'

services:

  mongo:
    image: mongo
    container_name: mongo-pokemon
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - pokemon-mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

  mongo-express:
    image: mongo-express
    container_name: mongo-express-pokemon
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
    - mongo

volumes:
  pokemon-mongo-data: